sort -k1,1 -k2,2n /share/Lab_Shaw/projects/TCGA/SpliceJunction/TCGA_GRTR1in10_SpliceJxn_Annotation/TCGA_HNSC_SpliceJxnAnnotation/BED/TCGA_HNSC_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed > sorted_TCGA_HNSC_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
bgzip -f sorted_TCGA_HNSC_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
tabix -f sorted_TCGA_HNSC_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed.gz
sort -k1,1 -k2,2n /share/Lab_Shaw/projects/TCGA/SpliceJunction/TCGA_GRTR1in10_SpliceJxn_Annotation/TCGA_MESO_SpliceJxnAnnotation/BED/TCGA_MESO_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed > sorted_TCGA_MESO_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
bgzip -f sorted_TCGA_MESO_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
tabix -f sorted_TCGA_MESO_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed.gz
sort -k1,1 -k2,2n /share/Lab_Shaw/projects/TCGA/SpliceJunction/TCGA_GRTR1in10_SpliceJxn_Annotation/TCGA_TGCT_SpliceJxnAnnotation/BED/TCGA_TGCT_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed > sorted_TCGA_TGCT_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
bgzip -f sorted_TCGA_TGCT_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
tabix -f sorted_TCGA_TGCT_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed.gz
sort -k1,1 -k2,2n /share/Lab_Shaw/projects/TCGA/SpliceJunction/TCGA_GRTR1in10_SpliceJxn_Annotation/TCGA_GBM_SpliceJxnAnnotation/BED/TCGA_GBM_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed > sorted_TCGA_GBM_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
bgzip -f sorted_TCGA_GBM_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
tabix -f sorted_TCGA_GBM_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed.gz
sort -k1,1 -k2,2n /share/Lab_Shaw/projects/TCGA/SpliceJunction/TCGA_GRTR1in10_SpliceJxn_Annotation/TCGA_ESCA_SpliceJxnAnnotation/BED/TCGA_ESCA_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed > sorted_TCGA_ESCA_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
bgzip -f sorted_TCGA_ESCA_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
tabix -f sorted_TCGA_ESCA_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed.gz
sort -k1,1 -k2,2n /share/Lab_Shaw/projects/TCGA/SpliceJunction/TCGA_GRTR1in10_SpliceJxn_Annotation/TCGA_SKCM_SpliceJxnAnnotation/BED/TCGA_SKCM_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed > sorted_TCGA_SKCM_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
bgzip -f sorted_TCGA_SKCM_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
tabix -f sorted_TCGA_SKCM_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed.gz
sort -k1,1 -k2,2n /share/Lab_Shaw/projects/TCGA/SpliceJunction/TCGA_GRTR1in10_SpliceJxn_Annotation/TCGA_STAD_SpliceJxnAnnotation/BED/TCGA_STAD_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed > sorted_TCGA_STAD_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
bgzip -f sorted_TCGA_STAD_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
tabix -f sorted_TCGA_STAD_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed.gz
sort -k1,1 -k2,2n /share/Lab_Shaw/projects/TCGA/SpliceJunction/TCGA_GRTR1in10_SpliceJxn_Annotation/TCGA_UVM_SpliceJxnAnnotation/BED/TCGA_UVM_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed > sorted_TCGA_UVM_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
bgzip -f sorted_TCGA_UVM_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
tabix -f sorted_TCGA_UVM_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed.gz
sort -k1,1 -k2,2n /share/Lab_Shaw/projects/TCGA/SpliceJunction/TCGA_GRTR1in10_SpliceJxn_Annotation/TCGA_CESC_SpliceJxnAnnotation/BED/TCGA_CESC_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed > sorted_TCGA_CESC_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
bgzip -f sorted_TCGA_CESC_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
tabix -f sorted_TCGA_CESC_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed.gz
sort -k1,1 -k2,2n /share/Lab_Shaw/projects/TCGA/SpliceJunction/TCGA_GRTR1in10_SpliceJxn_Annotation/TCGA_LIHC_SpliceJxnAnnotation/BED/TCGA_LIHC_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed > sorted_TCGA_LIHC_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
bgzip -f sorted_TCGA_LIHC_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
tabix -f sorted_TCGA_LIHC_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed.gz
sort -k1,1 -k2,2n /share/Lab_Shaw/projects/TCGA/SpliceJunction/TCGA_GRTR1in10_SpliceJxn_Annotation/TCGA_LUSC_SpliceJxnAnnotation/BED/TCGA_LUSC_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed > sorted_TCGA_LUSC_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
bgzip -f sorted_TCGA_LUSC_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
tabix -f sorted_TCGA_LUSC_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed.gz
sort -k1,1 -k2,2n /share/Lab_Shaw/projects/TCGA/SpliceJunction/TCGA_GRTR1in10_SpliceJxn_Annotation/TCGA_LUAD_SpliceJxnAnnotation/BED/TCGA_LUAD_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed > sorted_TCGA_LUAD_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
bgzip -f sorted_TCGA_LUAD_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
tabix -f sorted_TCGA_LUAD_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed.gz
sort -k1,1 -k2,2n /share/Lab_Shaw/projects/TCGA/SpliceJunction/TCGA_GRTR1in10_SpliceJxn_Annotation/TCGA_ACC_SpliceJxnAnnotation/BED/TCGA_ACC_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed > sorted_TCGA_ACC_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
bgzip -f sorted_TCGA_ACC_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
tabix -f sorted_TCGA_ACC_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed.gz
sort -k1,1 -k2,2n /share/Lab_Shaw/projects/TCGA/SpliceJunction/TCGA_GRTR1in10_SpliceJxn_Annotation/TCGA_PAAD_SpliceJxnAnnotation/BED/TCGA_PAAD_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed > sorted_TCGA_PAAD_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
bgzip -f sorted_TCGA_PAAD_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
tabix -f sorted_TCGA_PAAD_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed.gz
sort -k1,1 -k2,2n /share/Lab_Shaw/projects/TCGA/SpliceJunction/TCGA_GRTR1in10_SpliceJxn_Annotation/TCGA_KIRP_SpliceJxnAnnotation/BED/TCGA_KIRP_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed > sorted_TCGA_KIRP_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
bgzip -f sorted_TCGA_KIRP_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
tabix -f sorted_TCGA_KIRP_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed.gz
sort -k1,1 -k2,2n /share/Lab_Shaw/projects/TCGA/SpliceJunction/TCGA_GRTR1in10_SpliceJxn_Annotation/TCGA_PRAD_SpliceJxnAnnotation/BED/TCGA_PRAD_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed > sorted_TCGA_PRAD_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
bgzip -f sorted_TCGA_PRAD_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
tabix -f sorted_TCGA_PRAD_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed.gz
sort -k1,1 -k2,2n /share/Lab_Shaw/projects/TCGA/SpliceJunction/TCGA_GRTR1in10_SpliceJxn_Annotation/TCGA_KIRC_SpliceJxnAnnotation/BED/TCGA_KIRC_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed > sorted_TCGA_KIRC_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
bgzip -f sorted_TCGA_KIRC_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
tabix -f sorted_TCGA_KIRC_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed.gz
sort -k1,1 -k2,2n /share/Lab_Shaw/projects/TCGA/SpliceJunction/TCGA_GRTR1in10_SpliceJxn_Annotation/TCGA_BLCA_SpliceJxnAnnotation/BED/TCGA_BLCA_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed > sorted_TCGA_BLCA_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
bgzip -f sorted_TCGA_BLCA_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
tabix -f sorted_TCGA_BLCA_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed.gz
sort -k1,1 -k2,2n /share/Lab_Shaw/projects/TCGA/SpliceJunction/TCGA_GRTR1in10_SpliceJxn_Annotation/TCGA_THYM_SpliceJxnAnnotation/BED/TCGA_THYM_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed > sorted_TCGA_THYM_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
bgzip -f sorted_TCGA_THYM_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
tabix -f sorted_TCGA_THYM_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed.gz
sort -k1,1 -k2,2n /share/Lab_Shaw/projects/TCGA/SpliceJunction/TCGA_GRTR1in10_SpliceJxn_Annotation/TCGA_READ_SpliceJxnAnnotation/BED/TCGA_READ_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed > sorted_TCGA_READ_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
bgzip -f sorted_TCGA_READ_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
tabix -f sorted_TCGA_READ_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed.gz
sort -k1,1 -k2,2n /share/Lab_Shaw/projects/TCGA/SpliceJunction/TCGA_GRTR1in10_SpliceJxn_Annotation/TCGA_COAD_SpliceJxnAnnotation/BED/TCGA_COAD_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed > sorted_TCGA_COAD_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
bgzip -f sorted_TCGA_COAD_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
tabix -f sorted_TCGA_COAD_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed.gz
sort -k1,1 -k2,2n /share/Lab_Shaw/projects/TCGA/SpliceJunction/TCGA_GRTR1in10_SpliceJxn_Annotation/TCGA_DLBC_SpliceJxnAnnotation/BED/TCGA_DLBC_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed > sorted_TCGA_DLBC_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
bgzip -f sorted_TCGA_DLBC_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
tabix -f sorted_TCGA_DLBC_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed.gz
sort -k1,1 -k2,2n /share/Lab_Shaw/projects/TCGA/SpliceJunction/TCGA_GRTR1in10_SpliceJxn_Annotation/TCGA_OV_SpliceJxnAnnotation/BED/TCGA_OV_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed > sorted_TCGA_OV_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
bgzip -f sorted_TCGA_OV_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
tabix -f sorted_TCGA_OV_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed.gz
sort -k1,1 -k2,2n /share/Lab_Shaw/projects/TCGA/SpliceJunction/TCGA_GRTR1in10_SpliceJxn_Annotation/TCGA_THCA_SpliceJxnAnnotation/BED/TCGA_THCA_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed > sorted_TCGA_THCA_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
bgzip -f sorted_TCGA_THCA_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
tabix -f sorted_TCGA_THCA_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed.gz
sort -k1,1 -k2,2n /share/Lab_Shaw/projects/TCGA/SpliceJunction/TCGA_GRTR1in10_SpliceJxn_Annotation/TCGA_SARC_SpliceJxnAnnotation/BED/TCGA_SARC_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed > sorted_TCGA_SARC_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
bgzip -f sorted_TCGA_SARC_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
tabix -f sorted_TCGA_SARC_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed.gz
sort -k1,1 -k2,2n /share/Lab_Shaw/projects/TCGA/SpliceJunction/TCGA_GRTR1in10_SpliceJxn_Annotation/TCGA_PCPG_SpliceJxnAnnotation/BED/TCGA_PCPG_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed > sorted_TCGA_PCPG_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
bgzip -f sorted_CGA_PCPG_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
tabix -f sorted_TCGA_PCPG_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed.gz
sort -k1,1 -k2,2n /share/Lab_Shaw/projects/TCGA/SpliceJunction/TCGA_GRTR1in10_SpliceJxn_Annotation/TCGA_KICH_SpliceJxnAnnotation/BED/TCGA_KICH_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed > sorted_TCGA_KICH_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
bgzip -f sorted_TCGA_KICH_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
tabix -f sorted_TCGA_KICH_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed.gz
sort -k1,1 -k2,2n /share/Lab_Shaw/projects/TCGA/SpliceJunction/TCGA_GRTR1in10_SpliceJxn_Annotation/TCGA_CHOL_SpliceJxnAnnotation/BED/TCGA_CHOL_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed > sorted_TCGA_CHOL_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
bgzip -f sorted_TCGA_CHOL_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
tabix -f sorted_TCGA_CHOL_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed.gz
sort -k1,1 -k2,2n /share/Lab_Shaw/projects/TCGA/SpliceJunction/TCGA_GRTR1in10_SpliceJxn_Annotation/TCGA_UCEC_SpliceJxnAnnotation/BED/TCGA_UCEC_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed > sorted_TCGA_UCEC_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
bgzip -f sorted_TCGA_UCEC_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
tabix -f sorted_TCGA_UCEC_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed.gz
sort -k1,1 -k2,2n /share/Lab_Shaw/projects/TCGA/SpliceJunction/TCGA_GRTR1in10_SpliceJxn_Annotation/TCGA_BRCA_SpliceJxnAnnotation/BED/TCGA_BRCA_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed > sorted_TCGA_BRCA_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
bgzip -f sorted_TCGA_BRCA_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
tabix -f sorted_TCGA_BRCA_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed.gz
sort -k1,1 -k2,2n /share/Lab_Shaw/projects/TCGA/SpliceJunction/TCGA_GRTR1in10_SpliceJxn_Annotation/TCGA_LGG_SpliceJxnAnnotation/BED/TCGA_LGG_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed > sorted_TCGA_LGG_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
bgzip -f sorted_CGA_LGG_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
tabix -f sorted_TCGA_LGG_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed.gz
sort -k1,1 -k2,2n /share/Lab_Shaw/projects/TCGA/SpliceJunction/TCGA_GRTR1in10_SpliceJxn_Annotation/TCGA_UCS_SpliceJxnAnnotation/BED/TCGA_UCS_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed > sorted_TCGA_UCS_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
bgzip -f sorted_TCGA_UCS_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
tabix -f sorted_TCGA_UCS_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed.gz
sort -k1,1 -k2,2n /share/Lab_Shaw/projects/TCGA/SpliceJunction/TCGA_GRTR1in10_SpliceJxn_Annotation/TCGA_LAML_SpliceJxnAnnotation/BED/TCGA_LAML_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed > sorted_TCGA_LAML_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
bgzip -f sorted_TCGA_LAML_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed
tabix -f sorted_TCGA_LAML_SpliceJxn_noGTEx_noBM_GRTR1in10_AvgExpr.bed.gz